[build-menu]
FT_00_LB=Python Compile
FT_00_CM=~/GeanyOpts/ArduinoCompile-cli.py compile "%d/%f" 
FT_00_WD=
FT_01_LB=Python Upload
FT_01_CM=~/GeanyOpts/ArduinoCompile-cli.py upload "%d/%f"
FT_01_WD=
FT_02_LB=MakeLittleFS Pico 
FT_02_CM=/home/alain/.arduino15/packages/rp2040/tools/pqt-mklittlefs/4.1.0-1aec55e/mklittlefs -c %d/data -p 256 -b 4096 -s 3145728 ~/tmp/%elittlefs.bin
FT_02_WD=/home/alain/
FT_03_LB=Conversion .bin a uf2
FT_03_CM=/home/alain/.arduino15/packages/rp2040/tools/pqt-picotool/4.1.0-1aec55e/picotool uf2 convert ~/tmp/%elittlefs.bin -t bin  ~/tmp/%elittlefs.bin.uf2 -o 0x100fe000 --family data
FT_03_WD=
FT_04_LB=Upload Pico LittleFs
FT_04_CM=/home/alain/.arduino15/packages/rp2040/tools/pqt-python3/1.0.1-base-3a57aed-1/python3  /home/alain/.arduino15/packages/rp2040/hardware/rp2040/5.4.1/tools/uf2conv.py --serial ttyACM0 --family RP2040 ~/tmp/%elittlefs.bin.uf2 --deploy
FT_04_WD=
FT_05_LB=Esp8266 FS to .bin
FT_05_CM=/home/alain/.arduino15/packages/esp8266/tools/mklittlefs/3.1.0-gcc10.3-e5f9fec/mklittlefs  -c %d/data -b 8192 -p 256 -s 2072576 ~/tmp/esp8266_%e.bin
FT_05_WD=
EX_00_LB=_SauveCmd
EX_00_CM=~/GeanyOpts/ArduinoCompile-cli.py scompile "%d/%f" 
EX_00_WD=
EX_01_LB=Ajout Sys Op Id au source C
EX_01_CM=~/GeanyOpts/sourceTag.sh "%d/%f"
EX_01_WD=
EX_02_LB=Monitor ttyUSB0 & Log 
EX_02_CM=arduino-cli monitor -p /dev/ttyUSB0 -c BaudRate=115200 --timestamp | tee  -i -p --output-error=warn redir.txt
EX_02_WD=/home/alain/
EX_03_LB=Monitor ttyACM0 & Log
EX_03_CM=arduino-cli monitor -p /dev/ttyACM0 -c BaudRate=115200 --timestamp | tee  -i -p --output-error=warn redir.txt
EX_03_WD=/home/alain/
EX_04_LB=
EX_04_CM=
EX_04_WD=
